# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addTable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addTable.proto',
  package='protofile.baccarat.addTable',
  serialized_pb=_b('\n\x0e\x61\x64\x64Table.proto\x12\x1dprotofile.baccarat.addTable\"D\n\x0f\x61\x64\x64TableRequest\x12\x0f\n\x07tableId\x18\x01 \x02(\t\x12\x0f\n\x07videoId\x18\x02 \x02(\t\x12\x0f\n\x07limitId\x18\x03 \x02(\t\" \n\x10\x61\x64\x64TableResponse\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ADDTABLEREQUEST = _descriptor.Descriptor(
  name='addTableRequest',
  full_name='protofile.baccarat.addTable.addTableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableId', full_name='protofile.baccarat.addTable.addTableRequest.tableId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='videoId', full_name='protofile.baccarat.addTable.addTableRequest.videoId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limitId', full_name='protofile.baccarat.addTable.addTableRequest.limitId', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=117,
)


_ADDTABLERESPONSE = _descriptor.Descriptor(
  name='addTableResponse',
  full_name='protofile.baccarat.addTable.addTableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protofile.baccarat.addTable.addTableResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=151,
)

DESCRIPTOR.message_types_by_name['addTableRequest'] = _ADDTABLEREQUEST
DESCRIPTOR.message_types_by_name['addTableResponse'] = _ADDTABLERESPONSE

addTableRequest = _reflection.GeneratedProtocolMessageType('addTableRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDTABLEREQUEST,
  __module__ = 'addTable_pb2'
  # @@protoc_insertion_point(class_scope:protofile.baccarat.addTable.addTableRequest)
  ))
_sym_db.RegisterMessage(addTableRequest)

addTableResponse = _reflection.GeneratedProtocolMessageType('addTableResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDTABLERESPONSE,
  __module__ = 'addTable_pb2'
  # @@protoc_insertion_point(class_scope:protofile.baccarat.addTable.addTableResponse)
  ))
_sym_db.RegisterMessage(addTableResponse)


# @@protoc_insertion_point(module_scope)
