# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modifyVideo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modifyVideo.proto',
  package='protofile.baccarat.modifyVideo',
  serialized_pb=_b('\n\x11modifyVideo.proto\x12 protofile.baccarat.modifyVideo\"C\n\x12modifyVideoRequest\x12\x0f\n\x07videoId\x18\x01 \x02(\t\x12\x0f\n\x07\x62\x65tTime\x18\x02 \x02(\t\x12\x0b\n\x03url\x18\x03 \x02(\t\"#\n\x13modifyVideoResponse\x12\x0c\n\x04\x63ode\x18\x01 \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODIFYVIDEOREQUEST = _descriptor.Descriptor(
  name='modifyVideoRequest',
  full_name='protofile.baccarat.modifyVideo.modifyVideoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='videoId', full_name='protofile.baccarat.modifyVideo.modifyVideoRequest.videoId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='betTime', full_name='protofile.baccarat.modifyVideo.modifyVideoRequest.betTime', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='protofile.baccarat.modifyVideo.modifyVideoRequest.url', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=122,
)


_MODIFYVIDEORESPONSE = _descriptor.Descriptor(
  name='modifyVideoResponse',
  full_name='protofile.baccarat.modifyVideo.modifyVideoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protofile.baccarat.modifyVideo.modifyVideoResponse.code', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=159,
)

DESCRIPTOR.message_types_by_name['modifyVideoRequest'] = _MODIFYVIDEOREQUEST
DESCRIPTOR.message_types_by_name['modifyVideoResponse'] = _MODIFYVIDEORESPONSE

modifyVideoRequest = _reflection.GeneratedProtocolMessageType('modifyVideoRequest', (_message.Message,), dict(
  DESCRIPTOR = _MODIFYVIDEOREQUEST,
  __module__ = 'modifyVideo_pb2'
  # @@protoc_insertion_point(class_scope:protofile.baccarat.modifyVideo.modifyVideoRequest)
  ))
_sym_db.RegisterMessage(modifyVideoRequest)

modifyVideoResponse = _reflection.GeneratedProtocolMessageType('modifyVideoResponse', (_message.Message,), dict(
  DESCRIPTOR = _MODIFYVIDEORESPONSE,
  __module__ = 'modifyVideo_pb2'
  # @@protoc_insertion_point(class_scope:protofile.baccarat.modifyVideo.modifyVideoResponse)
  ))
_sym_db.RegisterMessage(modifyVideoResponse)


# @@protoc_insertion_point(module_scope)
