# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modifyTableLimit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modifyTableLimit.proto',
  package='protofile.baccarat.modifyTableLimit',
  serialized_pb=_b('\n\x16modifyTableLimit.proto\x12%protofile.baccarat.modifyTableLimit\"~\n\x17modifyTableLimitRequest\x12\x0f\n\x07limitId\x18\x01 \x02(\t\x12\x0b\n\x03num\x18\x02 \x02(\r\x12\x45\n\ntableLimit\x18\x03 \x03(\x0b\x32\x31.protofile.baccarat.modifyTableLimit.tableLimit\"J\n\ntableLimit\x12\x10\n\x08playtype\x18\x01 \x02(\r\x12\x14\n\x0cminval_cents\x18\x02 \x02(\r\x12\x14\n\x0cmaxval_cents\x18\x03 \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODIFYTABLELIMITREQUEST = _descriptor.Descriptor(
  name='modifyTableLimitRequest',
  full_name='protofile.baccarat.modifyTableLimit.modifyTableLimitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limitId', full_name='protofile.baccarat.modifyTableLimit.modifyTableLimitRequest.limitId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num', full_name='protofile.baccarat.modifyTableLimit.modifyTableLimitRequest.num', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tableLimit', full_name='protofile.baccarat.modifyTableLimit.modifyTableLimitRequest.tableLimit', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=191,
)


_TABLELIMIT = _descriptor.Descriptor(
  name='tableLimit',
  full_name='protofile.baccarat.modifyTableLimit.tableLimit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playtype', full_name='protofile.baccarat.modifyTableLimit.tableLimit.playtype', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minval_cents', full_name='protofile.baccarat.modifyTableLimit.tableLimit.minval_cents', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxval_cents', full_name='protofile.baccarat.modifyTableLimit.tableLimit.maxval_cents', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=267,
)

_MODIFYTABLELIMITREQUEST.fields_by_name['tableLimit'].message_type = _TABLELIMIT
DESCRIPTOR.message_types_by_name['modifyTableLimitRequest'] = _MODIFYTABLELIMITREQUEST
DESCRIPTOR.message_types_by_name['tableLimit'] = _TABLELIMIT

modifyTableLimitRequest = _reflection.GeneratedProtocolMessageType('modifyTableLimitRequest', (_message.Message,), dict(
  DESCRIPTOR = _MODIFYTABLELIMITREQUEST,
  __module__ = 'modifyTableLimit_pb2'
  # @@protoc_insertion_point(class_scope:protofile.baccarat.modifyTableLimit.modifyTableLimitRequest)
  ))
_sym_db.RegisterMessage(modifyTableLimitRequest)

tableLimit = _reflection.GeneratedProtocolMessageType('tableLimit', (_message.Message,), dict(
  DESCRIPTOR = _TABLELIMIT,
  __module__ = 'modifyTableLimit_pb2'
  # @@protoc_insertion_point(class_scope:protofile.baccarat.modifyTableLimit.tableLimit)
  ))
_sym_db.RegisterMessage(tableLimit)


# @@protoc_insertion_point(module_scope)
