# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modifyTable.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modifyTable.proto',
  package='protofile.baccarat.modifyTable',
  serialized_pb=_b('\n\x11modifyTable.proto\x12 protofile.baccarat.modifyTable\"U\n\x12modifyTableRequest\x12\x0f\n\x07tableId\x18\x01 \x02(\t\x12\x0f\n\x07videoId\x18\x02 \x02(\t\x12\x0f\n\x07limitId\x18\x03 \x02(\t\x12\x0c\n\x04\x66lag\x18\x04 \x02(\r\"#\n\x13modifyTableResponse\x12\x0c\n\x04\x63ode\x18\x01 \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODIFYTABLEREQUEST = _descriptor.Descriptor(
  name='modifyTableRequest',
  full_name='protofile.baccarat.modifyTable.modifyTableRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableId', full_name='protofile.baccarat.modifyTable.modifyTableRequest.tableId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='videoId', full_name='protofile.baccarat.modifyTable.modifyTableRequest.videoId', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limitId', full_name='protofile.baccarat.modifyTable.modifyTableRequest.limitId', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flag', full_name='protofile.baccarat.modifyTable.modifyTableRequest.flag', index=3,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=140,
)


_MODIFYTABLERESPONSE = _descriptor.Descriptor(
  name='modifyTableResponse',
  full_name='protofile.baccarat.modifyTable.modifyTableResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protofile.baccarat.modifyTable.modifyTableResponse.code', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=142,
  serialized_end=177,
)

DESCRIPTOR.message_types_by_name['modifyTableRequest'] = _MODIFYTABLEREQUEST
DESCRIPTOR.message_types_by_name['modifyTableResponse'] = _MODIFYTABLERESPONSE

modifyTableRequest = _reflection.GeneratedProtocolMessageType('modifyTableRequest', (_message.Message,), dict(
  DESCRIPTOR = _MODIFYTABLEREQUEST,
  __module__ = 'modifyTable_pb2'
  # @@protoc_insertion_point(class_scope:protofile.baccarat.modifyTable.modifyTableRequest)
  ))
_sym_db.RegisterMessage(modifyTableRequest)

modifyTableResponse = _reflection.GeneratedProtocolMessageType('modifyTableResponse', (_message.Message,), dict(
  DESCRIPTOR = _MODIFYTABLERESPONSE,
  __module__ = 'modifyTable_pb2'
  # @@protoc_insertion_point(class_scope:protofile.baccarat.modifyTable.modifyTableResponse)
  ))
_sym_db.RegisterMessage(modifyTableResponse)


# @@protoc_insertion_point(module_scope)
