# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modifyPersonalLimit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modifyPersonalLimit.proto',
  package='protofile.baccarat.modifyPersonalLimit',
  serialized_pb=_b('\n\x19modifyPersonalLimit.proto\x12(protofile.baccarat.modifyPersonalLimit\"\x8a\x01\n\x1amodifyPersonalLimitRequest\x12\x0f\n\x07limitId\x18\x01 \x02(\t\x12\x0b\n\x03num\x18\x02 \x02(\r\x12N\n\rpersonalLimit\x18\x03 \x03(\x0b\x32\x37.protofile.baccarat.modifyPersonalLimit.PersonalLimit\"M\n\rPersonalLimit\x12\x10\n\x08playtype\x18\x01 \x02(\r\x12\x14\n\x0cminval_cents\x18\x02 \x02(\r\x12\x14\n\x0cmaxval_cents\x18\x03 \x02(\r')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MODIFYPERSONALLIMITREQUEST = _descriptor.Descriptor(
  name='modifyPersonalLimitRequest',
  full_name='protofile.baccarat.modifyPersonalLimit.modifyPersonalLimitRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limitId', full_name='protofile.baccarat.modifyPersonalLimit.modifyPersonalLimitRequest.limitId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num', full_name='protofile.baccarat.modifyPersonalLimit.modifyPersonalLimitRequest.num', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='personalLimit', full_name='protofile.baccarat.modifyPersonalLimit.modifyPersonalLimitRequest.personalLimit', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=72,
  serialized_end=210,
)


_PERSONALLIMIT = _descriptor.Descriptor(
  name='PersonalLimit',
  full_name='protofile.baccarat.modifyPersonalLimit.PersonalLimit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='playtype', full_name='protofile.baccarat.modifyPersonalLimit.PersonalLimit.playtype', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minval_cents', full_name='protofile.baccarat.modifyPersonalLimit.PersonalLimit.minval_cents', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxval_cents', full_name='protofile.baccarat.modifyPersonalLimit.PersonalLimit.maxval_cents', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=289,
)

_MODIFYPERSONALLIMITREQUEST.fields_by_name['personalLimit'].message_type = _PERSONALLIMIT
DESCRIPTOR.message_types_by_name['modifyPersonalLimitRequest'] = _MODIFYPERSONALLIMITREQUEST
DESCRIPTOR.message_types_by_name['PersonalLimit'] = _PERSONALLIMIT

modifyPersonalLimitRequest = _reflection.GeneratedProtocolMessageType('modifyPersonalLimitRequest', (_message.Message,), dict(
  DESCRIPTOR = _MODIFYPERSONALLIMITREQUEST,
  __module__ = 'modifyPersonalLimit_pb2'
  # @@protoc_insertion_point(class_scope:protofile.baccarat.modifyPersonalLimit.modifyPersonalLimitRequest)
  ))
_sym_db.RegisterMessage(modifyPersonalLimitRequest)

PersonalLimit = _reflection.GeneratedProtocolMessageType('PersonalLimit', (_message.Message,), dict(
  DESCRIPTOR = _PERSONALLIMIT,
  __module__ = 'modifyPersonalLimit_pb2'
  # @@protoc_insertion_point(class_scope:protofile.baccarat.modifyPersonalLimit.PersonalLimit)
  ))
_sym_db.RegisterMessage(PersonalLimit)


# @@protoc_insertion_point(module_scope)
